#!/bin/bash

function verificare_ip() {
	nume="$1"
	adresa_ip="$2"
	server_DNS="$3"

	ip_real=$(nslookup "$nume" "$server_DNS" | grep 'Address: ' | grep -v '#' | awk 'NR==1{print $2}')
	if [[ -n "ip_real" && "$adresa_ip"!="$ip_real" ]]; then
		echo "Bogus IP for $nume in /etc/hosts"
	fi


} 

cat /etc/hosts | while read ip nume _; do

	if [[ -z $ip || $ip == \#* || $ip == *:* || $ip == 127.0.0.1 ]]; then
		continue
	fi

	server_DNS="8.8.8.8"
	verificare_ip "$nume" "$ip" "$server_DNS" 
done


